[package]
name = "square-1-solver-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
indicatif = "0.17.11"
rayon = "1.10.0"
bytemuck = "1.23.0"
image = "0.25.6"
imageproc = "0.25.0"
toml = "0.8.22"
serde = "1.0"
serde_derive = "1.0"